### ISSUE TITLE
no content response for OmicsDldata api

### ISSUE THREAD

**Issue by sergiocontrino** [ecrin-github/MDR_FuiPortal#11]
from renato:

> I’m getting "No content" responses for some requests and it seems a bit random depending on the combination of offset and size on the request URL. 
> Could it perhaps be some sort of proxy filter on your network?

**Comment by renatocjn** [comment]
Hi, just to give some examples.
![299950762-0bed8683-77b6-4796-9e2f-7c2369387c81](https://github.com/ecrin-github/MDR_FuiPortal/assets/2234715/cf2f5e41-f0c5-45c7-a82b-a8e759a415a7)
![299950489-087582a5-f132-4adc-b279-e5545f7a611a](https://github.com/ecrin-github/MDR_FuiPortal/assets/2234715/dda04f7c-72c4-4f31-afac-d1f6fd3d1099)

**Comment by sergiocontrino** [comment]
hi @renatocjn , the examples in the comment above disappeared!
thanks
sergio

**Comment by renatocjn** [comment]
It worked fine today :)

**Comment by sergiocontrino** [comment]
closing without action

**Comment by renatocjn** [comment]
Hi @sergiocontrino, it seems the problem has returned.
![image](https://github.com/ecrin-github/MDR_FuiPortal/assets/2234715/53f9f3dc-e469-4239-8c73-2398d71e9640)

**Comment by sergiocontrino** [comment]
thank you @renatocjn , we'll check this. how often do you run the query?

**Comment by renatocjn** [comment]
We run the query daily to check for updates.

**Comment by sergiocontrino** [comment]
@iPr0ger found that it happens when db busy with processes. he will improve error message.

**Comment by sergiocontrino** [comment]
@renatocjn please let us kow if we can close this issue

**Comment by renatocjn** [comment]
It hasn't happened in a while. Feel free to close it :)

**Comment by sergiocontrino** [comment]
thank you @renatocjn !

**Comment by renatocjn** [comment]
Hello @sergiocontrino 

It seems that the issue is back. Only change is the new crmdr.ecrin.org URL. Could you have a look if the export can be restored?
```shell
user@machine ~> https crmdr.ecrin.org/api/Study/OmicsDIdata/COVID/10/100                                                             
HTTP/1.1 204 No Content
Date: Wed, 25 Jun 2025 09:25:58 GMT
Server: Microsoft-IIS/10.0
Strict-Transport-Security: max-age=2592000



user@machine ~> https crmdr.ecrin.org/api/Study/OmicsDIdata/COVID/10/103                                                             
HTTP/1.1 204 No Content
Date: Wed, 25 Jun 2025 09:26:00 GMT
Server: Microsoft-IIS/10.0
Strict-Transport-Security: max-age=2592000



user@machine ~> https crmdr.ecrin.org/api/Study/OmicsDIdata/COVID/10/200                                                             
HTTP/1.1 204 No Content
Date: Wed, 25 Jun 2025 09:26:02 GMT
Server: Microsoft-IIS/10.0
Strict-Transport-Security: max-age=2592000
```

**Comment by renatocjn** [comment]
Hi @sergiocontrino, did you have the time to look into this?

**Comment by renatocjn** [comment]
No worries, whenever you have a bit of time. Biggest side effect of this is the data at the covid portal being out of date.
Like here: <https://www.covid19dataportal.org/search/research-infrastructures?db=ecrin-mdr-covid>.

**Comment by sergiocontrino** [comment]
dear @renatocjn , sorry for the long wait. fortunately @iPr0ger came to the rescue.
it should be fine now, but please let me know if any problem. i keep this open for now.

**Comment by renatocjn** [comment]
Hi @sergiocontrino and @iPr0ger, thank you for the working on this.

It's working perfectly when I access on the browser but I get timeouts when I do a curl, wget or use the java HTTP client. Is it possible that there is a firewall or proxy in between blocking non-browser requests?

**Comment by sergiocontrino** [comment]
hi @renatocjn , apologies for the slow motion, we are in full grant submission season.
we checked and it appears to for work for us (also ouotside our network and using curl/wget). could you confirm on your side? thanks!

**Comment by renatocjn** [comment]
Hi @sergiocontrino, sorry for the delay in answering this. The original issue was sorted, but we were still randomly getting an error response. After trying different things, we changed our code to run one request at a time, and things seem to work. Feel free to close this issue :)

**Comment by sergiocontrino** [comment]
thank you @renatocjn , great :). i'll close. thank you @sgoryanin !

**Comment by vijayvenkateshs** [comment]
Hi Team, 

I think the issue is back again but now the whole study API is not returning any meta data and i am able to reproduce the issue consistantly. I am not exactly sure if this is the same issue or is it something else or if it is an expected behaviour.

The URL in question is : https://crmdr.ecrin.org/api/Study/OmicsDIdata/COVID/

Thanks,
Vijay

**Comment by sergiocontrino** [comment]
hi @vijayvenkateshs ,
the api seems to be working for us.
please note that must be called with type (COVID) and also with offset and limit, so a working url is , e.g.

https://crmdr.ecrin.org/api/Study/OmicsDIdata/COVID/10/100

please let me know
thanks
sergio

**Comment by kelseyneis** [comment]
Hi @sergiocontrino, that URL works for me, but we're not sure what to set these values to. Do you know what the limit and offset should be for the EBI Search feed?

**Comment by sergiocontrino** [comment]
hi @kelseyneis , i think it depends how you are looping through the request. i suppose it is in your code already.
i think you get the data in batches, e.g. from 1 to 100 (0, 100), from 101 to 200 (100, 100), etc).
not sure what the best batch size is. please let us know if this does not help.

**Comment by kelseyneis** [comment]
@sergiocontrino you're correct, I looked again and now see we have a chunk size of 1000. Will give that a go, thanks!

**Comment by sergiocontrino** [comment]
dear @renatocjn , @kelseyneis , @vijayvenkateshs 
we are changing the application and moving the current version from crmdr.ecrin.org to legacymdr.ecrin.org
if you are still using the api, please adjust your code to use the new url.
we are planning the change for tomorrow 03/09/2026
please let me know that you received this message.
we will send you an updated call for the new setup soon.
thanks!
sergio

**Comment by kelseyneis** [comment]
> dear [@renatocjn](https://github.com/renatocjn) , [@kelseyneis](https://github.com/kelseyneis) , [@vijayvenkateshs](https://github.com/vijayvenkateshs) we are changing the application and moving the current version from crmdr.ecrin.org to legacymdr.ecrin.org if you are still using the api, please adjust your code to use the new url. we are planning the change for tomorrow 03/09/2026 please let me know that you received this message. we will send you an updated call for the new setup soon. thanks! sergio

Dear @sergiocontrino , Thanks for the heads up, we'll update it on our end.

**Comment by sergiocontrino** [comment]
dear @kelseyneis , we just did the swap, so you should use legacymdr.ecrin.org (https://legacymdr.ecrin.org/), when propagation has reached you.
please let us know if something is not working.
we'll check the requirement of your call and send you how to get them from the new app, hopefully soon. thanks!

**Comment by kelseyneis** [comment]
Hi @sergiocontrino , our indexing process ran successfully last night with the new url.
