### ISSUE TITLE
add search by country

### ISSUE THREAD

**Issue by sergiocontrino** [ecrin-github/MDR_FuiPortal#15]
request from  Lesya Baudoin <lesya.baudoin@inserm.fr>

> possibility to search the interface by country, very useful for our project.

note from @scanhamman 

> As regards her question I think (stress think, it would need checking) that it would be relatively easy to add country selection to the API, though any written list of countries would first need to be changed to a series of integer codes before presentation to the database, and the names would have to equate to those known to the system so that the conversion to ids could take place.

**Comment by sergiocontrino** [comment]
filtering by country is already possible.
is it possible to remove the condition that is not possible to filter without keyword search?
is it too dangerous ? (i.e. should we have some mechanism to cancel queries if taking too long/too much resources?)

**Comment by lesyabaudoin** [comment]
happy you come back to this issue ! And yes, absolutely, it would be really useful to filter by country without keyword search !:-)

**Comment by sergiocontrino** [comment]
@iPr0ger added api (paginated), which returns the complete study object

ex. with france and germany, page1, with pageSize =10
https://newmdr.ecrin.org/api/Study/ByCountries?countries=France%2CGermany&pageNumber=1&pageSize=10

will add the total number of records in the result.

he is also working on a not paginated version, retrieving only study ids by one country.

**Comment by ericjeangirard** [comment]
that seems great!
with only one country though, i got an error
https://newmdr.ecrin.org/api/Study/ByCountries?countries=France&pageNumber=1&pageSize=10

**Comment by iPr0ger** [comment]
@ericjeangirard thanks for the issue report.
Now search with one country should be working correctly.

**Comment by sergiocontrino** [comment]
postponing the non paginated version, depending on demand. closing for now
