### ISSUE TITLE
NDI4Health request: mapping ECRIN items (and values) to NDI4H ones

### ISSUE THREAD

**Issue by sergiocontrino** [ecrin-github/MDR_FuiPortal#33]
summary from NDI4H 

> We've previously agreed on creating a reverse crosswalk or mapping between two schemas. Initially, we worked on mapping using an older version of the ECRIN schema. Just before his departure , Steve undertook a preliminary mapping exercise with the ECRIN version 8, committing to a full and detailed mapping in the future by the other  technical team from ECRIN. Your expected  task involves mapping all ECRIN items, including their values where feasible, or at the very least, the mandatory ECRIN items and their values, to our corresponding items and values. We'll handle the reverse mapping on our end.

- [ ] get the list of MDR v8 terms (and values), detailing if mandatory
- [ ] idem for NDI4H v 3.3
- [ ] provide table of correspondences

for MDR v8: https://zenodo.org/records/8368709

for NDI4H v 3.3: https://zenodo.org/records/10793093
or  https://art-decor.org/ad/#/nfdhtfcov19-/datasets/dataset

**Comment by sergiocontrino** [comment]
this is the [reverse comparison](https://docs.google.com/spreadsheets/d/1Xi_KnxkT476sGeX3lprC-97TWf73PJgWDWd9dY6Bd18/edit?usp=sharing) done by NDI4H

and here the NDI4H [metadata schema (MDS)](https://docs.google.com/presentation/d/1Qr0jDCRzrvCXHFMKpVQr9SyZs7u1cOeBs96codHETec/edit?usp=sharing)

**Comment by sergiocontrino** [comment]
@Swarnalathaa working on this, here the [summary](https://docs.google.com/spreadsheets/d/1Hy96ZUUPpuXoJgjnvcdi2u8SKWuIz--7/edit?usp=sharing&ouid=115002300780325040589&rtpof=true&sd=true)

**Comment by Swarnalathaa** [comment]
we had the meeting with Qi WU(qi.wu@h-its.org) and it seems that most of their mandatory fields in the schema matches with the ECRIN Schema
